## 이미지 다루기

In [4]:
import imageio

img_arr = imageio.imread('bobby.jpg')
img_arr

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21960\296171344.py:3: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread('bobby.jpg')

array([[[ 77,  45,  22],
        [ 77,  45,  22],
        [ 78,  46,  21],
        ...,
        [118,  78,  52],
        [117,  77,  51],
        [116,  76,  51]],

       [[ 75,  43,  20],
        [ 76,  44,  21],
        [ 77,  45,  20],
        ...,
        [118,  78,  52],
        [117,  77,  51],
        [116,  76,  50]],

       [[ 74,  39,  17],
        [ 75,  41,  16],
        [ 77,  43,  18],
        ...,
        [119,  80,  51],
        [117,  77,  51],
        [116,  76,  50]],

       ...,

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [172, 122,  51],
        [174, 124,  53],
        [174, 124,  53]],

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [173, 123,  54],
        [174, 124,  55],
        [174, 124,  55]],

       [[215, 165,  78],
        [216, 166,  79],
        [217, 167,  80],
        ...,
        [159, 108,  42],
        [158, 107,  41],
        [158, 107,  41]]], dtype=uint8)

In [6]:
img_arr.shape

(720, 1280, 3)

In [8]:
import torch

img = torch.from_numpy(img_arr)
img.shape

torch.Size([720, 1280, 3])

In [10]:
out = img.permute(2, 0, 1)
out

tensor([[[ 77,  77,  78,  ..., 118, 117, 116],
         [ 75,  76,  77,  ..., 118, 117, 116],
         [ 74,  75,  77,  ..., 119, 117, 116],
         ...,
         [215, 216, 217,  ..., 172, 174, 174],
         [215, 216, 217,  ..., 173, 174, 174],
         [215, 216, 217,  ..., 159, 158, 158]],

        [[ 45,  45,  46,  ...,  78,  77,  76],
         [ 43,  44,  45,  ...,  78,  77,  76],
         [ 39,  41,  43,  ...,  80,  77,  76],
         ...,
         [165, 166, 167,  ..., 122, 124, 124],
         [165, 166, 167,  ..., 123, 124, 124],
         [165, 166, 167,  ..., 108, 107, 107]],

        [[ 22,  22,  21,  ...,  52,  51,  51],
         [ 20,  21,  20,  ...,  52,  51,  50],
         [ 17,  16,  18,  ...,  51,  51,  50],
         ...,
         [ 78,  79,  80,  ...,  51,  53,  53],
         [ 78,  79,  80,  ...,  54,  55,  55],
         [ 78,  79,  80,  ...,  42,  41,  41]]], dtype=torch.uint8)

In [12]:
out.shape

torch.Size([3, 720, 1280])

In [14]:
img.size(), img.stride()

(torch.Size([720, 1280, 3]), (3840, 3, 1))

In [16]:
out.size(), out.stride()

(torch.Size([3, 720, 1280]), (1, 3840, 3))

In [18]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [20]:
import os

In [52]:
data_dir = './image_cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1].lower() == '.png']
filenames

['cat1.png', 'cat2.png', 'cat3.png']

In [54]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2,0,1)
    img_t = img_t[:3]   #투명도 알파채널까지 있는 이미지에서도 RGB 첫 세개 채널만 유지
    batch[i] = img_t

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21960\644946099.py:2: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread(os.path.join(data_dir, filename))

In [56]:
batch

tensor([[[[156, 152, 124,  ..., 150, 149, 158],
          [174, 134, 165,  ..., 120, 136, 138],
          [127, 156, 107,  ..., 131, 143, 164],
          ...,
          [116, 130, 129,  ..., 127, 118, 112],
          [129, 130, 123,  ..., 115, 121, 114],
          [129, 123, 118,  ..., 113, 121, 120]],

         [[139, 135, 109,  ..., 135, 135, 147],
          [160, 119, 149,  ..., 105, 122, 124],
          [113, 140,  90,  ..., 118, 129, 152],
          ...,
          [ 99, 110, 111,  ..., 117, 108, 103],
          [111, 111, 106,  ..., 106, 112, 105],
          [111, 104, 102,  ..., 103, 110, 111]],

         [[129, 123,  98,  ..., 131, 132, 145],
          [155, 110, 137,  ..., 102, 119, 121],
          [104, 132,  80,  ..., 112, 125, 146],
          ...,
          [ 93, 108, 105,  ..., 125, 115, 108],
          [108, 108,  98,  ..., 110, 117, 110],
          [107,  98,  95,  ..., 108, 115, 116]]],


        [[[202, 193, 190,  ...,  13,  13,  12],
          [199, 192, 189,  ...,  14,  14,  14],
          [198, 193, 188,  ...,  12,  12,  12],
          ...,
          [ 93,  82,  76,  ...,  36,  36,  36],
          [ 75,  68, 101,  ...,  36,  36,  37],
          [ 85, 103,  90,  ...,  36,  37,  38]],

         [[151, 139, 133,  ...,   9,   9,   8],
          [151, 140, 134,  ...,  11,  11,  11],
          [152, 143, 134,  ...,  11,  11,  11],
          ...,
          [ 57,  45,  39,  ...,  26,  26,  26],
          [ 33,  26,  59,  ...,  26,  26,  27],
          [ 40,  58,  45,  ...,  26,  27,  28]],

         [[ 68,  53,  44,  ...,   6,   6,   5],
          [ 67,  54,  44,  ...,   6,   6,   6],
          [ 67,  56,  44,  ...,   6,   6,   6],
          ...,
          [ 31,  19,  12,  ...,  17,  17,  17],
          [ 11,   2,  35,  ...,  17,  17,  18],
          [ 19,  37,  22,  ...,  17,  18,  19]]],


        [[[238, 238, 238,  ..., 214, 215, 215],
          [238, 238, 238,  ..., 214, 215, 215],
          [238, 238, 238,  ..., 214, 215, 215],
          ...,
          [214, 213, 212,  ..., 187, 190, 193],
          [214, 213, 212,  ..., 186, 190, 192],
          [214, 213, 212,  ..., 186, 190, 192]],

         [[195, 195, 195,  ..., 173, 175, 175],
          [195, 195, 195,  ..., 173, 175, 175],
          [195, 195, 195,  ..., 173, 175, 175],
          ...,
          [128, 127, 126,  ..., 100, 103, 106],
          [128, 127, 126,  ...,  99, 103, 105],
          [128, 127, 126,  ...,  99, 103, 105]],

         [[137, 137, 137,  ..., 125, 126, 126],
          [137, 137, 137,  ..., 125, 126, 126],
          [137, 137, 137,  ..., 125, 126, 126],
          ...,
          [ 79,  78,  77,  ...,  64,  68,  72],
          [ 79,  78,  77,  ...,  64,  69,  71],
          [ 79,  78,  77,  ...,  65,  69,  72]]]], dtype=torch.uint8)

In [58]:
batch.shape

torch.Size([3, 3, 256, 256])

In [60]:
batch = batch.float()
batch /= 255.0
batch

tensor([[[[0.6118, 0.5961, 0.4863,  ..., 0.5882, 0.5843, 0.6196],
          [0.6824, 0.5255, 0.6471,  ..., 0.4706, 0.5333, 0.5412],
          [0.4980, 0.6118, 0.4196,  ..., 0.5137, 0.5608, 0.6431],
          ...,
          [0.4549, 0.5098, 0.5059,  ..., 0.4980, 0.4627, 0.4392],
          [0.5059, 0.5098, 0.4824,  ..., 0.4510, 0.4745, 0.4471],
          [0.5059, 0.4824, 0.4627,  ..., 0.4431, 0.4745, 0.4706]],

         [[0.5451, 0.5294, 0.4275,  ..., 0.5294, 0.5294, 0.5765],
          [0.6275, 0.4667, 0.5843,  ..., 0.4118, 0.4784, 0.4863],
          [0.4431, 0.5490, 0.3529,  ..., 0.4627, 0.5059, 0.5961],
          ...,
          [0.3882, 0.4314, 0.4353,  ..., 0.4588, 0.4235, 0.4039],
          [0.4353, 0.4353, 0.4157,  ..., 0.4157, 0.4392, 0.4118],
          [0.4353, 0.4078, 0.4000,  ..., 0.4039, 0.4314, 0.4353]],

         [[0.5059, 0.4824, 0.3843,  ..., 0.5137, 0.5176, 0.5686],
          [0.6078, 0.4314, 0.5373,  ..., 0.4000, 0.4667, 0.4745],
          [0.4078, 0.5176, 0.3137,  ..., 0.4392, 0.4902, 0.5725],
          ...,
          [0.3647, 0.4235, 0.4118,  ..., 0.4902, 0.4510, 0.4235],
          [0.4235, 0.4235, 0.3843,  ..., 0.4314, 0.4588, 0.4314],
          [0.4196, 0.3843, 0.3725,  ..., 0.4235, 0.4510, 0.4549]]],


        [[[0.7922, 0.7569, 0.7451,  ..., 0.0510, 0.0510, 0.0471],
          [0.7804, 0.7529, 0.7412,  ..., 0.0549, 0.0549, 0.0549],
          [0.7765, 0.7569, 0.7373,  ..., 0.0471, 0.0471, 0.0471],
          ...,
          [0.3647, 0.3216, 0.2980,  ..., 0.1412, 0.1412, 0.1412],
          [0.2941, 0.2667, 0.3961,  ..., 0.1412, 0.1412, 0.1451],
          [0.3333, 0.4039, 0.3529,  ..., 0.1412, 0.1451, 0.1490]],

         [[0.5922, 0.5451, 0.5216,  ..., 0.0353, 0.0353, 0.0314],
          [0.5922, 0.5490, 0.5255,  ..., 0.0431, 0.0431, 0.0431],
          [0.5961, 0.5608, 0.5255,  ..., 0.0431, 0.0431, 0.0431],
          ...,
          [0.2235, 0.1765, 0.1529,  ..., 0.1020, 0.1020, 0.1020],
          [0.1294, 0.1020, 0.2314,  ..., 0.1020, 0.1020, 0.1059],
          [0.1569, 0.2275, 0.1765,  ..., 0.1020, 0.1059, 0.1098]],

         [[0.2667, 0.2078, 0.1725,  ..., 0.0235, 0.0235, 0.0196],
          [0.2627, 0.2118, 0.1725,  ..., 0.0235, 0.0235, 0.0235],
          [0.2627, 0.2196, 0.1725,  ..., 0.0235, 0.0235, 0.0235],
          ...,
          [0.1216, 0.0745, 0.0471,  ..., 0.0667, 0.0667, 0.0667],
          [0.0431, 0.0078, 0.1373,  ..., 0.0667, 0.0667, 0.0706],
          [0.0745, 0.1451, 0.0863,  ..., 0.0667, 0.0706, 0.0745]]],


        [[[0.9333, 0.9333, 0.9333,  ..., 0.8392, 0.8431, 0.8431],
          [0.9333, 0.9333, 0.9333,  ..., 0.8392, 0.8431, 0.8431],
          [0.9333, 0.9333, 0.9333,  ..., 0.8392, 0.8431, 0.8431],
          ...,
          [0.8392, 0.8353, 0.8314,  ..., 0.7333, 0.7451, 0.7569],
          [0.8392, 0.8353, 0.8314,  ..., 0.7294, 0.7451, 0.7529],
          [0.8392, 0.8353, 0.8314,  ..., 0.7294, 0.7451, 0.7529]],

         [[0.7647, 0.7647, 0.7647,  ..., 0.6784, 0.6863, 0.6863],
          [0.7647, 0.7647, 0.7647,  ..., 0.6784, 0.6863, 0.6863],
          [0.7647, 0.7647, 0.7647,  ..., 0.6784, 0.6863, 0.6863],
          ...,
          [0.5020, 0.4980, 0.4941,  ..., 0.3922, 0.4039, 0.4157],
          [0.5020, 0.4980, 0.4941,  ..., 0.3882, 0.4039, 0.4118],
          [0.5020, 0.4980, 0.4941,  ..., 0.3882, 0.4039, 0.4118]],

         [[0.5373, 0.5373, 0.5373,  ..., 0.4902, 0.4941, 0.4941],
          [0.5373, 0.5373, 0.5373,  ..., 0.4902, 0.4941, 0.4941],
          [0.5373, 0.5373, 0.5373,  ..., 0.4902, 0.4941, 0.4941],
          ...,
          [0.3098, 0.3059, 0.3020,  ..., 0.2510, 0.2667, 0.2824],
          [0.3098, 0.3059, 0.3020,  ..., 0.2510, 0.2706, 0.2784],
          [0.3098, 0.3059, 0.3020,  ..., 0.2549, 0.2706, 0.2824]]]])

## 3차원 이미지

In [65]:
import imageio

dir_path = './volumetric-dicom_2-LUNG 3.0  B70f-04083'
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

Reading DICOM (examining files): 1/99 files (1.0%99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 99/99  (100.0%)

(99, 512, 512)

In [69]:
vol = torch.from_numpy(vol_arr).float()
vol.shape

torch.Size([99, 512, 512])

In [71]:
vol = torch.unsqueeze(vol, 0)
vol.shape

torch.Size([1, 99, 512, 512])

In [73]:
vol

tensor([[[[ -985.,  -990.,  -999.,  ..., -1017., -1008.,  -971.],
          [-1016.,  -984.,  -963.,  ..., -1000., -1009.,  -999.],
          [-1024., -1008.,  -996.,  ...,  -979., -1021.,  -987.],
          ...,
          [ -920.,  -942.,  -944.,  ...,  -893.,  -917.,  -955.],
          [ -871.,  -879.,  -905.,  ...,  -895.,  -869.,  -867.],
          [ -876.,  -855.,  -873.,  ...,  -933.,  -982.,  -936.]],

         [[ -982.,  -989., -1020.,  ...,  -988.,  -977.,  -980.],
          [-1015.,  -969.,  -980.,  ...,  -981.,  -974., -1016.],
          [-1020.,  -978.,  -972.,  ...,  -988.,  -993., -1015.],
          ...,
          [ -880.,  -854.,  -924.,  ...,  -909.,  -829.,  -829.],
          [ -907.,  -868.,  -928.,  ...,  -909.,  -901.,  -894.],
          [ -885.,  -850.,  -899.,  ...,  -977.,  -964.,  -991.]],

         [[-1022., -1011.,  -983.,  ..., -1013.,  -980.,  -967.],
          [-1022., -1005., -1012.,  ...,  -948.,  -966., -1008.],
          [ -991.,  -965.,  -993.,  ...,  -964., -1011.,  -996.],
          ...,
          [ -858.,  -899.,  -950.,  ...,  -939.,  -868.,  -827.],
          [ -948.,  -914.,  -918.,  ...,  -968.,  -978.,  -946.],
          [ -921.,  -874.,  -914.,  ...,  -898.,  -910.,  -934.]],

         ...,

         [[ -979.,  -906., -1016.,  ..., -1010.,  -896.,  -928.],
          [-1024.,  -943.,  -863.,  ...,  -956.,  -953., -1022.],
          [-1021., -1024.,  -988.,  ...,  -971., -1008.,  -962.],
          ...,
          [ -780.,  -824.,  -931.,  ...,  -874.,  -887.,  -890.],
          [ -837., -1002.,  -977.,  ...,  -880.,  -930.,  -886.],
          [ -991.,  -978.,  -867.,  ...,  -921.,  -903.,  -913.]],

         [[ -977.,  -999.,  -975.,  ..., -1024.,  -987.,  -847.],
          [ -980.,  -995.,  -916.,  ...,  -996.,  -915.,  -967.],
          [-1010., -1024.,  -958.,  ...,  -990.,  -979., -1002.],
          ...,
          [ -836.,  -909.,  -926.,  ...,  -909.,  -794.,  -917.],
          [ -912., -1001.,  -872.,  ...,  -947.,  -866.,  -881.],
          [ -998.,  -834.,  -782.,  ...,  -964.,  -852.,  -922.]],

         [[-1003., -1017., -1023.,  ..., -1010.,  -984.,  -968.],
          [ -938., -1013., -1009.,  ...,  -988.,  -999.,  -958.],
          [ -980.,  -995.,  -982.,  ..., -1005.,  -938.,  -916.],
          ...,
          [ -859.,  -928.,  -867.,  ...,  -968.,  -896.,  -861.],
          [ -886.,  -965.,  -849.,  ...,  -943.,  -895.,  -864.],
          [ -915.,  -865.,  -809.,  ...,  -963.,  -928.,  -856.]]]])

## 데이터 테이블

In [88]:
import pandas as pd
df = pd.read_csv('winequality-white.csv', sep=';', quotechar='"')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [90]:
import csv
import numpy as np

wineq_numpy = np.loadtxt('winequality-white.csv', dtype=np.float32, delimiter=";",skiprows=1)

wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [92]:
wineq_numpy.shape

(4898, 12)

In [94]:
col_list = next(csv.reader(open('winequality-white.csv'),delimiter=';'))
col_list

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [96]:
wineq = torch.from_numpy(wineq_numpy)

wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [98]:
data = wineq[:,:-1]  #모든 행과 마지막을 제와한 모든 열을 선택
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [100]:
target = wineq[:,-1]  #모든 행과 마지막 열을 선택
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [102]:
target = wineq[:,-1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [108]:
target = (wineq[:,-1]-1).long()
target_onehot = torch.zeros(target.shape[0], 10)

target_onehot.scatter_(1, target.unsqueeze(1), 1.0)
target_onehot

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [110]:
data_mean = torch.mean(data, dim=0)
data_mean

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01])

In [112]:
data_var = torch.var(data, dim=0)
data_var

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])

In [114]:
data_normalized = (data-data_mean) / torch.sqrt(data_var)
data_normalized

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [118]:
target = wineq[:,-1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [120]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))

In [122]:
bad_data = data[bad_indexes]
bad_data.shape

torch.Size([20, 11])

In [126]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)]
good_data = data[target >= 7]
bad_data.shape, mid_data.shape, good_data.shape

(torch.Size([20, 11]), torch.Size([3818, 11]), torch.Size([1060, 11]))

In [128]:
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42

In [130]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:,6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)

predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(2727))

In [132]:
actual_indexes = target > 5

actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(3258))

In [136]:
n_matches = torch.sum(actual_indexes & predicted_indexes).item()
n_predicted = torch.sum(predicted_indexes).item()
n_actual = torch.sum(actual_indexes).item()

n_matches, n_matches/n_predicted, n_matches/n_actual

(2018, 0.74000733406674, 0.6193984039287906)

## 시계열 데이터

In [141]:
bikes_numpy = np.loadtxt('hour-fixed.csv', dtype=np.float32, delimiter=",", skiprows=1, 
                         converters={1: lambda x: float(x[8:10])})    #첫번째 열의 일자 문자열을 숫자로 변환
bikes = torch.from_numpy(bikes_numpy)
bikes

tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 3.0000e+00, 1.3000e+01,
         1.6000e+01],
        [2.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 8.0000e+00, 3.2000e+01,
         4.0000e+01],
        [3.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 5.0000e+00, 2.7000e+01,
         3.2000e+01],
        ...,
        [1.7377e+04, 3.1000e+01, 1.0000e+00,  ..., 7.0000e+00, 8.3000e+01,
         9.0000e+01],
        [1.7378e+04, 3.1000e+01, 1.0000e+00,  ..., 1.3000e+01, 4.8000e+01,
         6.1000e+01],
        [1.7379e+04, 3.1000e+01, 1.0000e+00,  ..., 1.2000e+01, 3.7000e+01,
         4.9000e+01]])

In [145]:
bikes.shape

torch.Size([17520, 17])

In [151]:
df2 = pd.read_csv('hour-fixed.csv', sep=',')
df2

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17515,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17516,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17517,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17518,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17519,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [153]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [155]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [157]:
daily_bikes = daily_bikes.transpose(1,2)
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 17, 24]), (408, 1, 17))

In [165]:
first_day = bikes[:24].long()  #하루, 24시간 데이터 추출
first_day.shape

torch.Size([24, 17])

In [177]:
first_day[:,9]  # 그 중 날씨 상태 열 확인

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2])

In [179]:
weather_onehot = torch.zeros(first_day.shape[0], 4)

In [181]:
weather_onehot.scatter_(dim=1, index=first_day[:,9].unsqueeze(1).long()-1, value=1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [189]:
torch.cat((bikes[:24], weather_onehot),1).shape

torch.Size([24, 21])

## 텍스트 표현하기

In [192]:
with open('1342-0.txt', encoding='utf8') as f:
    text = f.read()

In [194]:
lines = text.split('\n')
line = lines[200]
line

'“Impossible, Mr. Bennet, impossible, when I am not acquainted with him'

In [198]:
letter_t = torch.zeros(len(line), 128) #아스키코드 제한인 128로 설정
for i, letter in enumerate(line.lower().strip()):
    letter_index = ord(letter) if ord(letter) < 128 else 0  #아스키에 없는 문자는 버림
    letter_t[i][letter_index] = 1
letter_t.shape

torch.Size([70, 128])

In [200]:
letter_t

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [202]:
def clean_words(input_str):
    punctuation = '.,;:"!?”“_-'
    word_list = input_str.lower().replace('\n',' ').split()
    word_list = [word.strip(punctuation) for word in word_list]
    return word_list

words_in_line = clean_words(line)
line, words_in_line

('“Impossible, Mr. Bennet, impossible, when I am not acquainted with him',
 ['impossible',
  'mr',
  'bennet',
  'impossible',
  'when',
  'i',
  'am',
  'not',
  'acquainted',
  'with',
  'him'])

In [204]:
word_list = sorted(set(clean_words(text)))
word2index_dict = {word: i for (i, word) in enumerate(word_list)}

len(word2index_dict), word2index_dict['impossible']

(7261, 3394)

In [206]:
word_t = torch.zeros(len(words_in_line), len(word2index_dict))
for i, word in enumerate(words_in_line):
    word_index = word2index_dict[word]
    word_t[i][word_index] = 1
    print('{:2} {:4} {}'.format(i, word_index, word))
    
print(word_t.shape)

 0 3394 impossible
 1 4305 mr
 2  813 bennet
 3 3394 impossible
 4 7078 when
 5 3315 i
 6  415 am
 7 4436 not
 8  239 acquainted
 9 7148 with
10 3215 him
torch.Size([11, 7261])